#!/bin/bash
# -copyright-
#-# 
#-# plasmastorm: Storms of drifting items: snow, leaves, rain.
#-# 
#-# Copyright (C) 2024 Mark Capella
#-# 
#-# This program is free software: you can redistribute it and/or modify
#-# it under the terms of the GNU General Public License as published by
#-# the Free Software Foundation, either version 3 of the License, or
#-# (at your option) any later version.
#-# 
#-# This program is distributed in the hope that it will be useful,
#-# but WITHOUT ANY WARRANTY; without even the implied warranty of
#-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#-# GNU General Public License for more details.
#-# 
#-# You should have received a copy of the GNU General Public License
#-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-# 


curdir=`pwd`
if [ -f Makefile ] ; then
   make distclean
fi
rm -f configure
# Create generatedShellCmd.sh for the Pixmaps folder
(
cd src/Pixmaps
echo -n "# -copyright" > generatedShellCmd.sh
echo "-" >> generatedShellCmd.sh
echo "EXTRA_DIST = \\" >> generatedShellCmd.sh
echo "generatedShellCmd.sh \\" >> generatedShellCmd.sh
ls *.xpm *.xbm *.svg | sed 's/$/ \\/' | sed '$s/\\//' >> generatedShellCmd.sh
)

./addCopyright.sh Makefile.am afterburner/Makefile.am addCopyright.sh bootstrap \
   configure.ac simplemake.sh
find src \( -name '*.c' -o -name '*.h' -o -name '*.am' -o -name '*.xpm' -o -name '*.xbm' \
   -o -name '*.xml' -o -name '*.sh' -o -name '*.cpp' -o -name '*.inc' \) -print0 | xargs -0 ./addCopyright.sh

cd $curdir

date +%s > bootdate

autoreconf -fvi || exit 1
(
echo
echo removing po/*.gmo end po/*.po
rm -f po/*.gmo po/*.po

echo
echo Removing Odd Tempfiles.
rm configure~ config.h.in~ autom4te.cache/* po/*.po~

echo
echo "Copying pofiles/*.po to po/"
cp pofiles/*.po po
cd po

pofiles=`echo *.po`
languages=`echo $pofiles | sed 's/\.po//g'`

echo
echo "Created po/LINGUAS:"
   echo '# Set of available languages.' > LINGUAS
   echo "$languages" >> LINGUAS
cat LINGUAS
echo 
)

echo "$0 done"
